# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

settingInterval_cpp <- function(y, delta_, s_, J_) {
    .Call(`_BayesSurvive_settingInterval_cpp`, y, delta_, s_, J_)
}

matProdVec <- function(x, y) {
    .Call(`_BayesSurvive_matProdVec`, x, y)
}

sumMatProdVec <- function(x, y) {
    .Call(`_BayesSurvive_sumMatProdVec`, x, y)
}

updateBH_cpp <- function(x_, beta_, J_, ind_r_d_, hPriorSh_, d_, c0_) {
    .Call(`_BayesSurvive_updateBH_cpp`, x_, beta_, J_, ind_r_d_, hPriorSh_, d_, c0_)
}

updateBH_list_cpp <- function(x_, beta_, J_, ind_r_d_, hPriorSh_, d_, c0_) {
    .Call(`_BayesSurvive_updateBH_list_cpp`, x_, beta_, J_, ind_r_d_, hPriorSh_, d_, c0_)
}

calJpost_helper_cpp <- function(cbtau, x_, beta_, h_, hPriorSh_, c0_, J_, ind_r_d_, ind_d_) {
    .Call(`_BayesSurvive_calJpost_helper_cpp`, cbtau, x_, beta_, h_, hPriorSh_, c0_, J_, ind_r_d_, ind_d_)
}

updateRP_genomic_cpp <- function(p, x_, J_, ind_r_, ind_d_, ind_r_d_, be_, be_prop_sd_scale, ga_, h_, tau, cb) {
    .Call(`_BayesSurvive_updateRP_genomic_cpp`, p, x_, J_, ind_r_, ind_d_, ind_r_d_, be_, be_prop_sd_scale, ga_, h_, tau, cb)
}

